apiVersion: v1
kind: Deployment
metadata: 
  name:  mosqitto-depl 
  labels: 
    app: mosquitto
spec:
  replicas: 1 
  selector: 
    matchLabel:
      app: mosquitto
  template:
    metadata: 
      labels:
        app: mosquitto
    spec:
      containers:
        - image:  eclipse-mosquitto:1.6.2
          name:  mosquitto
          ports:
          - name:  mosquitto-port
            port:  1883
            protocol: TCP
#mosquitto without volume 
