apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: kubernetes-example
spec:
  rules:
  - host: exapmle.com
    http:
      paths:
      - backend: 
          service:
            name: expamle-service
            port:
              number: 80
