apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: test  #set username on base64 here 
  MONGO_INITDB_ROOT_PASSWORD: test  #set password on base64 here 